time python3 janKenPuzzle.py < tests/light/input/input00.txt > stdout.txt && git diff --ignore-space-at-eol tests/light/output/output00.txt stdout.txt
time python3 janKenPuzzle.py < tests/light/input/input01.txt > stdout.txt && git diff --ignore-space-at-eol tests/light/output/output01.txt stdout.txt
time python3 janKenPuzzle.py < tests/light/input/input02.txt > stdout.txt && git diff --ignore-space-at-eol tests/light/output/output02.txt stdout.txt
time python3 janKenPuzzle.py < tests/light/input/input03.txt > stdout.txt && git diff --ignore-space-at-eol tests/light/output/output03.txt stdout.txt
time python3 janKenPuzzle.py < tests/light/input/input04.txt > stdout.txt && git diff --ignore-space-at-eol tests/light/output/output04.txt stdout.txt
time python3 janKenPuzzle.py < tests/light/input/input05.txt > stdout.txt && git diff --ignore-space-at-eol tests/light/output/output05.txt stdout.txt
time python3 janKenPuzzle.py < tests/light/input/input06.txt > stdout.txt && git diff --ignore-space-at-eol tests/light/output/output06.txt stdout.txt
time python3 janKenPuzzle.py < tests/light/input/input07.txt > stdout.txt && git diff --ignore-space-at-eol tests/light/output/output07.txt stdout.txt
time python3 janKenPuzzle.py < tests/light/input/input08.txt > stdout.txt && git diff --ignore-space-at-eol tests/light/output/output08.txt stdout.txt
time python3 janKenPuzzle.py < tests/light/input/input09.txt > stdout.txt && git diff --ignore-space-at-eol tests/light/output/output09.txt stdout.txt
